name: cloud-storage

services:

  postgres:
    image: postgres:16
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${CS_DATABASE}
      - POSTGRES_USER=${CS_DB_USER}
      - POSTGRES_PASSWORD=${CS_DB_PASS}
    networks:
      cloud_storage_net:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${CS_MINIO_USER}
      - MINIO_ROOT_PASSWORD=${CS_MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      cloud_storage_net:

volumes:
  postgres_data:
networks:
  cloud_storage_net: