name: cloud-storage

services:

  postgres:
    image: postgres:16
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${CS_DATABASE}
      - POSTGRES_USER=${CS_DB_USER}
      - POSTGRES_PASSWORD=${CS_DB_PASS}
    networks:
      cloud_storage_net:

volumes:
  postgres_data:
networks:
  cloud_storage_net: