spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: ${CS_DB_DRIVER_CLASSNAME}
    url: jdbc:${CS_DB_DRIVER}://${CS_DB_HOST}:${CS_DB_PORT}/${CS_DATABASE}
    username: ${CS_DB_USER}
    password: ${CS_DB_PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: ${CS_HIBERNATE_DIALECT}
  liquibase:
    enabled: false

jwt:
  issuer: localhost
  secret: ${JWT_SECRET}
  lifetime: 10h

logging:
  level:
    root: info
    com.pustovalov.cloudstorage: debug

minio:
  url: ${CS_MINIO_URL}
  access-key: ${CS_MINIO_ACCESS_KEY}
  secret-key: ${CS_MINIO_SECRET_KEY}