spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: ${CS_DB_DRIVER_CLASSNAME}
    url: jdbc:${CS_DB_DRIVER}://${CS_DB_HOST}:${CS_DB_PORT}/${CS_DATABASE}
    username: ${CS_DB_USER}
    password: ${CS_DB_PASS}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.sql

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  lifetime: 24h

minio:
  url: ${CS_MINIO_URL}
  access-key: ${CS_MINIO_ACCESS_KEY}
  secret-key: ${CS_MINIO_SECRET_KEY}
  default-bucket: prod-storage
